#!/bin/zsh
apply_pywal_colors() {
    if [ -f ~/.pywal_on ]; then
        if [ -d "$HOME/.cache/wal" ]; then
            (cat ~/.cache/wal/sequences &)
            # source ~/.cache/wal/colors-tty.sh
            export PYWAL=1
        fi
    else
        if [ "${PYWAL:-0}" -eq 1 ]; then
            reset
        fi
        export PYWAL=0
    fi
}

apply_pywal_colors
