export SHELL=$(which zsh)
export TMUX_SOCKET_NAME="tmux-$RANDOM"

# if [ "$(tty)" = "/dev/tty1" ]; then
#     clear
#     echo "Starting Hyprland..."
#     exec start-hyprland >> /tmp/hyprland.log
# else
#     if [[ $(tty) =~ ^/dev/tty[0-9]+$ ]]; then
#         echo "Restoring Hyprland..."
#         ~/.scripts/restore_hyprland.sh
#     fi
# fi

# eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/config.toml)"  # Oh My Posh
eval "$(starship init zsh)"                                                # Starship

# rustup
# eval "$(rustup completions zsh)"

# FZF
# source <(fzf --zsh)

# Zoxide
# eval "$(zoxide init --cmd cd zsh)"

# Yazi
function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
else
    export EDITOR='nvim'
fi

# Keybindings
bindkey -v
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# Use Neovim to read man pages
export MANPAGER='nvim +Man!'

# History settings
HISTSIZE=1000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# cd
setopt autocd

# Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zstyle ':completion:*' matcher-list \
    'm:{a-zA-Z}={A-Za-z}' \
    'r:|[._-]=* r:|=*' \
    'l:|=* r:|=*'

# Plugins
zinit ice wait
zinit load Aloxaf/fzf-tab
zinit ice wait
zinit load zsh-users/zsh-autosuggestions
zinit ice wait
zinit load zdharma-continuum/fast-syntax-highlighting

source ~/.config/zsh/functions
source ~/.config/zsh/aliases

startup
