animations {
    enabled = true
  
    bezier = quick, 0.33, 0.7, 0.6, 0.98
    bezier = linear, 1, 1, 1, 1
  
    animation = windowsIn, 1, 1.6, quick, popin
    animation = windowsOut, 1, 1.7, quick, popin
    animation = windowsMove, 1, 1.2, quick, slide
    animation = border, 1, 1, linear
    animation = borderangle, 1, 30, linear, once
    animation = workspaces, 1, 1.2, quick, fade
}
