general {
    lock_cmd = swaylock --daemonize
    before_sleep_cmd = swaylock --daemonize
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener { # Decrease brightness after 2 minutes 40 seconds
    timeout = 160
    on-timeout = brightnessctl s 10%-
    on-resume = brightnessctl s 10%+
}

listener { # Lock after 2 minutes 50 seconds
    timeout = 170
    on-timeout = loginctl lock-session
}

listener { # Switch off screen after 3 minutes
    timeout = 180
    on-timeout = run_if_not_plaing.sh hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener { # Suspend after 10 minutes
    timeout = 600
    on-timeout = systemctl suspend
}
