# Floating
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:title ^(iwgtk)$
windowrule = float on, match:title ^(Media viewer)$
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(file_progress)$
windowrule = float on, match:class ^(confirm)$
windowrule = float on, match:class ^(dialog)$
windowrule = float on, size 800 600, match:class ^(download)$
windowrule = float on, match:class ^(notification)$
windowrule = float on, match:class ^(error)$
windowrule = float on, match:class ^(confirmreset)$
windowrule = float on, size 800 600, match:title ^(Open File)$
windowrule = float on, match:title ^(branchdialog)$
windowrule = float on, match:title ^(Confirm to replace files)$
windowrule = float on, match:title ^(File Operation Progress)$
windowrule = float on, size 800 600, match:title ^(Save File)$
windowrule = float on, match:initial_class ^(file-png)$
windowrule = float on, match:class ^(com.gabm.satty)$

windowrule = float on, size 500 600, match:initial_title ^(Search Actions)$, match:initial_class ^(gimp)$

# Floating class
windowrule = float on, size 800 600, center on, match:class (floating)

# Size
windowrule = size 800 600, match:title ^(Volume Control)$
windowrule = size 400 1080, match:class ^(sidebar)
windowrule = size 1000 900, match:class ^(blender)
windowrule = center 1, match:class ^(blender)
windowrule = fullscreen on, match:class (fullscreen)

# Wine
windowrule = size 20 20, match:class ^(explorer.exe)$, match:title ^()$
windowrule = rounding 0, match:class ^(explorer.exe)$, match:title ^()$
windowrule = move monitor_w-20 0, match:class ^(explorer.exe)$, match:title ^()$
windowrule = float on, match:class (.*\.exe)$ # float all .exes

windowrule = idle_inhibit focus, match:class ^(mpv)$

windowrule = border_size 0, no_shadow on, match:class ^(ulauncher)$

# xwaylandvideobridge
windowrule = opacity 0.0 override 0.0 override, no_anim on, no_initial_focus on, match:class ^(xwaylandvideobridge)$
#windowrule = nofocus,class:^(xwaylandvideobridge)$
windowrule = float on, match:initial_class ^(iwgtk)$

# KDE Connect
windowrule = float on, border_size 0, no_shadow on, size (monitor_w*1) (monitor_h*1), no_initial_focus on, no_anim on, no_blur on, match:class ^(org.kde.kdeconnect.daemon)$
windowrule = float on, size (monitor_w*0.25) (monitor_h*0.2), match:initial_title ^(Receiving files — KDE Connect Daemon)$
windowrule = float on, size (monitor_w*0.25) (monitor_h*0.2), match:initial_title ^(Receiving file — KDE Connect Daemon)$

# Pinned
windowrule = opacity 100% 100%, match:pin 1

# Layers
layerrule {
    name = swaync_slide
    match:namespace = swaync-control-center

    animation = slide right
}

layerrule {
    name = screenshot_fix
    match:namespace = hyprpicker

    no_anim = true
}

layerrule {
    name = screenshot_fix
    match:namespace = selection

    no_anim = true
}
