[[manager.prepend_keymap]]
on   = "<C-A-w>"
run  = '''
  shell 'set_wallpaper.sh $1'
'''
desc = "Set the current image as a wallpaper"

[[manager.prepend_keymap]]
on  = "<C-n>"
run = '''
	shell 'dragon-drop -x -i -T "$1"'
'''

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
