[plugin]
append_previewers = [{ name = "*", run = "hexyl" }]

[opener]
app_image = [
  { run = '"$0"', orphan = true, desc = "Run AppImage", for = "unix" },
]
java = [
  { run = 'java -jar "$@"', desc = "Run with Java", orphan = true, for = "unix" },
]

[open]
prepend_rules = [
  { name = "*.AppImage", use = ["app_image"] },
  { name = "*.jar", use = ["java"] },
]
